export const completedArr = [
  {
    id: 0,
    completionDay: "Mon",
    completionDate: "5",
    habitId: 1,
    done: false,
  },
  {
    id: 1,
    completionDay: "Tue",
    completionDate: "6",
    habitId: 1,
    done: true,
  },
  {
    id: 2,
    completionDay: "Wed",
    completionDate: "7",
    habitId: 1,
    done: false,
  },
  {
    id: 3,
    completionDay: "Thu",
    completionDate: "8",
    habitId: 1,
    done: true,
  },
  {
    id: 4,
    completionDay: "Fri",
    completionDate: "9",
    habitId: 1,
    done: true,
  },
  {
    id: 5,
    completionDay: "Sat",
    completionDate: "10",
    habitId: 1,
    done: false,
  },
  {
    id: 6,
    completionDay: "Sun",
    completionDate: "11",
    habitId: 1,
    done: true,
  },
  {
    id: 7,
    completionDay: "Mon",
    completionDate: "12",
    habitId: 1,
    done: false,
  },
  {
    id: 8,
    completionDay: "Tue",
    completionDate: "13",
    habitId: 1,
    done: true,
  },
  {
    id: 9,
    completionDay: "Tue",
    completionDate: "13",
    habitId: 2,
    done: true,
  },
  {
    id: 9,
    completionDay: "Tue",
    completionDate: "14",
    habitId: 2,
    done: true,
  },
  {
    id: 10,
    completionDay: "Tue",
    completionDate: "13",
    habitId: 3,
    done: true,
  },
];
